# Generated by Django 3.1.4 on 2021-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_no', models.IntegerField()),
                ('bot_name', models.CharField(max_length=100)),
                ('table_no', models.IntegerField()),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('food_type', models.CharField(max_length=30)),
                ('speed_of_the_bot', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_delivered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Final Delivery',
                'verbose_name_plural': 'Final Deliveries',
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
    ]
