# Generated by Django 3.1.4 on 2021-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211026_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldelivery',
            name='time',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=50),
        ),
    ]
