# Generated by Django 3.1.4 on 2021-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bot_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldelivery',
            name='food_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='finaldelivery',
            name='speed_of_the_bot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
