# Generated by Django 3.1.4 on 2021-11-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_finaldelivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=4, max_digits=500, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True)),
                ('angle', models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bot')),
            ],
            options={
                'verbose_name': 'Bot locations',
                'ordering': ('-id',),
            },
        ),
    ]
